### ISSUE TITLE
NPM Install Broken

### ISSUE THREAD

**Issue by ryangrose** [trustedkey/trustedkey.js#1]
Following the install guide [here](https://trustedkey.github.io/RelyingParty-Tutorial/#getting-started) we should install from the old repo at bitbucket but that doesn't seem to exist.

Changing the url to the new repo as such
`sudo npm install https://github.com/trustedkey/trustedkey.js.git`
results in
```
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/trustedkey/trustedkey.js.git /home/ryan/.npm/_cacache/tmp/git-clone-52c096a1
npm ERR! /home/ryan/.npm/_cacache/tmp/git-clone-52c096a1/.git: Permission denied
npm ERR!
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ryan/.npm/_logs/2018-01-08T23_50_51_444Z-debug.log
```

The log contents look like this:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'https://github.com/trustedkey/trustedkey.js.git' ]
2 info using npm@5.5.1
3 info using node@v9.3.0
4 verbose config Skipping project config: /home/ryan/.npmrc. (matches userconfig)
5 verbose npm-session d9ca26daf585b5cb
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData error for git+https://github.com/trustedkey/trustedkey.js.git Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/trustedkey/trustedkey.js.git /home/ryan/.npm/_cacache/tmp/git-clone-52c096a1
8 silly fetchPackageMetaData /home/ryan/.npm/_cacache/tmp/git-clone-52c096a1/.git: Permission denied
9 verbose stack Error: Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/trustedkey/trustedkey.js.git /home/ryan/.npm/_cacache/tmp/git-clone-52c096a1
9 verbose stack /home/ryan/.npm/_cacache/tmp/git-clone-52c096a1/.git: Permission denied
9 verbose stack
9 verbose stack     at ChildProcess.exithandler (child_process.js:272:12)
9 verbose stack     at ChildProcess.emit (events.js:159:13)
9 verbose stack     at maybeClose (internal/child_process.js:943:16)
9 verbose stack     at Socket.stream.socket.on (internal/child_process.js:363:11)
9 verbose stack     at Socket.emit (events.js:159:13)
9 verbose stack     at Pipe._handle.close [as _onclose] (net.js:568:12)
10 verbose cwd /home/ryan
11 verbose Linux 4.10.0-42-generic
12 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "https://github.com/trustedkey/trustedkey.js.git"
13 verbose node v9.3.0
14 verbose npm  v5.5.1
15 error code 1
16 error Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/trustedkey/trustedkey.js.git /home/ryan/.npm/_cacache/tmp/git-clone-52c096a1
16 error /home/ryan/.npm/_cacache/tmp/git-clone-52c096a1/.git: Permission denied
17 verbose exit [ 1, true ]
```

Running the failed command with sudo
`sudo /usr/bin/git clone --depth=1 -q -b master https://github.com/trustedkey/trustedkey.js.git /home/ryan/.npm/_cacache/tmp/git-clone-52c096a` 
seems to work, but it's unclear if this will work for/with npm

Running the command without sudo also breaks with permission denied errors on mkdir and a prompt saying "Please try running this command again as root/Administrator."

Running on Ubuntu 16.04, npm version 5.5.1, node version 9.3.0

**Comment by adisbladis** [comment]
Hi @ryangrose. 

It looks to me like you are having some faulty file system permissions in `~/.npm`. Perhaps from running some operation as root before?

I recommend changing ownership of `~/.npm` using `sudo chown -R ryan ~/.npm` and try using `npm install` again.

**Comment by lionello** [comment]
@ryangrose You shouldn't use `sudo` with npm. This will mess up your permissions, for sure. I suggest you `sudo` remove the `~/.npm` and `node_modules` folders and try without sudo.

**Comment by adisbladis** [comment]
Triage: Are you still having any issues?

**Comment by lionello** [comment]
Closing this issue because lack of repro details.
